def author():
    print( """
    _      _    _    _____                      _ _         
    | |    | |  | |  / ____|                    (_) |        
    | |    | |__| | | (___   ___  ___ _   _ _ __ _| |_ _   _ 
    | |    |  __  |  \___ \ / _ \/ __| | | | '__| | __| | | |
    | |____| |  | |  ____) |  __/ (__| |_| | |  | | |_| |_| |
    |______|_|  |_| |_____/ \___|\___|\__,_|_|  |_|\__|\__, |
                                                        __/ |
                                                        |___/ 
    """ )
def banner():
    print("======================================================")
    print("                      Commands                       ")
    print("======================================================")
    print("System:")
    print("======================================================")
    print("exec                      - Execute a cmd command ")
    print("help                      - Display all available commands")
    print("browser                   - Open a website in the client machine's browser")
    print("turnoffmon                - Turn off the monitor")
    print("turnonmon                 - Turn on the monitor")
    print("reboot                    - Reboot the system")
    print("drivers                   - List all drivers on the PC")
    print("usbdrivers                - List all connected USB devices")
    print("sendmessage               - Send a message box with the specified text")
    print("cpu_cores                 - Display the number of CPU cores")
    print("systeminfo                - Display basic system information (via cmd)")
    print("tasklist                  - List all running system tasks")
    print("localtime                 - Display the current system time")
    print("curpid                    - Get the PID of the client's process")
    print("sysinfo                   - Display basic system information")
    print("shutdown                  - Shutdown the client's PC")
    print("monitors                  - List all connected monitors")
    print("geolocate                 - Get the location of the computer")
    print("exit                      - Terminate the session of RAT")
    print("======================================================")
    print("Shell:")
    print("======================================================")
    print("pwd                       - Get the current working directory")
    print("shell                     - Execute commands via cmd")
    print("cd                        - Change directory")
    print("cd ..                     - Change directory back")
    print("dir                       - List all files in the current directory")
    print("cd --                     - Switch back to the first directory when the connection was established with the client machine")
    print("======================================================")
    print("Network:")
    print("======================================================")
    print("ipconfig                  - Display the local IP")
    print("portscan                  - Perform a port scan")
    print("profiles                  - Display network profiles")
    print("collect_wifipass          - Get Wi-Fi passwords")
    print("======================================================")
    print("Input devices:")
    print("======================================================")
    print("keylogger_start           - Start keylogger")
    print("keylogger_send            - Send captured keystrokes")
    print("keylogger_stop            - Stop keylogger")
    print("clipboard_start           - Start clipboard capture")
    print("clipboard_stop            - Stop clipboard capture")
    print("clipboard_send            - Send captured clipboard contents")
    print("disable (--keyboard/--mouse/--all) - Disable input devices")
    print("enable (--keyboard/--mouse/--all)  - Enable input devices")
    print("======================================================")
    print("Video:")
    print("======================================================")
    print("screenshare               - Oversee remote PC")
    print("webcam                    - Capture webcam video")
    print("breakstream               - Break webcam/screenshare stream")
    print("screenshot                - Capture a screenshot")
    print("webcam_snap               - Capture a webcam photo")
    print("lock_pc                   - Disable all input and display a lock image")
    print("======================================================")
    print("Files:")
    print("======================================================")
    print("delfile <file>            - Delete a file")
    print("editfile <file> <text>    - Edit a file")
    print("createfile <file>         - Create a file")
    print("download   <file>         - Download a file")
    print("upload     <file>          - Upload a file")
    print("mkdir <dirname>           - Create a directory")
    print("rmdir <dirname>           - Remove a directory")
    print("readfile <file>           - Read from a file")
    print("encrypt              - Encrypt the entered file")
    print("======================================================")
